### ISSUE TITLE
IntelliJ auto-saving feature throws java.lang.InterruptedException on exit

### ISSUE THREAD

**Issue by nelsonni** [ChangeOrientedProgrammingEnvironment/IntelliJ-test-recorder#23]
This issue is related to race conditions in thread concurrency, and is likely caused by one of the implemented listeners overriding thread-safe code that forces the write-buffer-to-file process to execute prior to closing the IDE.

When running the plugin, I can consistently recreate this issue by doing the following:
1. Open file in editor window.
2. Modify file in editor window.
3. Close IntelliJ IDE before the auto-save feature is activated.
4. Observe the following error reported to logs:

```
[  19457]  ERROR - til.concurrency.QueueProcessor - java.lang.InterruptedException 
com.intellij.openapi.application.RuntimeInterruptedException: java.lang.InterruptedException
    at com.intellij.openapi.application.impl.ApplicationImpl.startRead(ApplicationImpl.java:917)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:870)
    at com.intellij.openapi.vcs.changes.VcsDirtyScopeManagerImpl.convertPaths(VcsDirtyScopeManagerImpl.java:151)
    at com.intellij.openapi.vcs.changes.VcsDirtyScopeManagerImpl.filePathsDirty(VcsDirtyScopeManagerImpl.java:169)
    at com.intellij.openapi.vcs.changes.VcsDirtyScopeVfsListener$FileAndDirsCollector.markDirty(VcsDirtyScopeVfsListener.java:251)
    at com.intellij.openapi.vcs.changes.VcsDirtyScopeVfsListener$FileAndDirsCollector.access$300(VcsDirtyScopeVfsListener.java:196)
    at com.intellij.openapi.vcs.changes.VcsDirtyScopeVfsListener$1.run(VcsDirtyScopeVfsListener.java:92)
    at com.intellij.openapi.util.ZipperUpdater$1.run(ZipperUpdater.java:65)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:298)
    at com.intellij.util.concurrency.QueueProcessor$RunnableConsumer.consume(QueueProcessor.java:295)
    at com.intellij.util.concurrency.QueueProcessor$2$1.run(QueueProcessor.java:110)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:107)
    at com.intellij.util.concurrency.QueueProcessor$2.consume(QueueProcessor.java:104)
    at com.intellij.util.concurrency.QueueProcessor$3$1.run(QueueProcessor.java:215)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.concurrency.QueueProcessor$3.run(QueueProcessor.java:212)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
    at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:772)
    at com.intellij.openapi.application.impl.ApplicationImpl.startRead(ApplicationImpl.java:913)
    ... 27 more
[  19468]  ERROR - til.concurrency.QueueProcessor - IntelliJ IDEA 14.1.5  Build #IC-141.2735.5 
[  19468]  ERROR - til.concurrency.QueueProcessor - JDK: 1.8.0_60 
[  19468]  ERROR - til.concurrency.QueueProcessor - VM: Java HotSpot(TM) 64-Bit Server VM 
[  19469]  ERROR - til.concurrency.QueueProcessor - Vendor: Oracle Corporation 
[  19469]  ERROR - til.concurrency.QueueProcessor - OS: Linux 
```

**Comment by nelsonni** [comment]
After turning off successive listeners and observing the behavior of the plugin following the steps outlined in the description of this issue, I found that the following listener is to blame:

`edu.oregonstate.cope.intellijListener.listeners.FileEditorListener`

This is part of [method-activity](/ChangeOrientedProgrammingEnvironment/IntelliJ-test-recorder/tree/method-activity) branch. I will fix it within that branch, since these changes haven't been pulled into the [master](/ChangeOrientedProgrammingEnvironment/IntelliJ-test-recorder/tree/master) branch yet.

**Comment by denysaw** [comment]
@nelsonni Hello there! =) So... have you managed to fix that? I'm having same bug few times a day with PhpStorm 2018.2. Not very funny bug ( IDE stucks for few minutes and then stucks on each Ctrl+S... Until I restart it.

**Comment by nelsonni** [comment]
@denysaw Unfortunately, I haven't worked on this project in 3 years. I believe this bug was slated to be fixed as part of a larger feature development in the`method-activity` branch. I believe that ran into a roadblock due to some missing functionality in the IntelliJ plugin API (might be fixed now). However, I am not the primary maintainer on this project. The COPE project page ([link](http://cope.eecs.oregonstate.edu/)) should have contact information for reaching the team.
